var Constants = {}
Constants.BILLBOARD_URL = "http://www.billboard.com/charts/hot-100"
Constants.MAIN_CLASS = "#main div .chart-data .container"
Constants.SONG_DIV = ".chart-row .chart-row__primary .chart-row__main-display"
Constants.SONG_NAME = ".chart-row__container .chart-row__title .chart-row__song"
Constants.SONG_RANK = ".chart-row__rank .chart-row__current-week"
Constants.SONG_ARTIST =".chart-row__container .chart-row__title .chart-row__artist"
Constants.SONG_IMAGE = ".chart-row__image"
module.exports = Constants
