var Constants = {}
Constants.BILLBOARD_URL = "https://www.billboard.com/charts/hot-100"
Constants.MAIN_CLASS = "#main #charts .charts-container .chart-list.container .chart-list__elements"
Constants.SONG_DIV = ".chart-list__element .chart-element__wrapper"
Constants.SONG_NAME = ".chart-element__information .chart-element__information__song"
Constants.SONG_RANK = ".chart-element__rank .chart-element__rank__number"
Constants.SONG_ARTIST =".chart-element__information .chart-element__information__artist"
Constants.SONG_IMAGE = ".chart-element__image"
module.exports = Constants
